on:
  push:
    tags:
      - "v*.*.*"

name: Publish Releases

jobs:
  build_publish:
    name: Publishing Tasks
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl

        include:
          - target: x86_64-unknown-linux-musl
            host_os: ubuntu-latest

    runs-on: ${{ matrix.host_os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: Prepare
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          mkdir mypubdir4
          rustup target add ${{ matrix.target }}
          cargo install cross --git https://github.com/cross-rs/cross.git --rev e281947

      - name: Build
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          cross build --all-features --release --target ${{ matrix.target }}
          zip -j mypubdir4/dns2socks-${{ matrix.target }}.zip target/${{ matrix.target }}/release/dns2socks README.md

      - name: Publish
        if: ${{ !cancelled() }}
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: mypubdir4/*

      - name: Abort on error
        if: ${{ failure() }}
        run: echo "Publish job failed" && false
